### ISSUE TITLE
wayland support on linux maybe?

### ISSUE THREAD

**Issue by nabulator** [puyonexus/puyovs#44]
Title. I'm getting a segfault on my wayland installation on arch. Probably related to the fact I'm using wayland.

**Comment by jchv** [comment]
Sorry about that. Indeed, I am sure Wayland support is broken. In the meantime, you might be able to use XWayland by setting `WAYLAND_DISPLAY=` in the shell before running, or perhaps setting `QT_QPA_PLATFORM=xcb`.

That said, we really should resolve this and some other issues and cut a new release. The current latest version is still the closed source version... So if you go online with the open source code, you will not see anybody at the moment.

**Comment by sagehane** [comment]
Still experiencing this on latest commit with `nix run` and trying to go to offline mode:
```
$ nix run
Bin Path:  "/nix/store/ggrrip35yybqd0na5vapmxw4r60aja1c-puyovs-32/bin"
Asset Path:  "/nix/store/ggrrip35yybqd0na5vapmxw4r60aja1c-puyovs-32/share/puyovs"
Reloading languages...
Warning: "Language/ChineseSimplified.json" contains a UTF-8 BOM. Discarded.
Warning: "Language/French.json" contains a UTF-8 BOM. Discarded.
Warning: "Language/Japanese.json" contains a UTF-8 BOM. Discarded.
Warning: "Language/Spanish.json" contains a UTF-8 BOM. Discarded.
QMetaObject::connectSlotsByName: No matching signal for on_StartupDialog_Finished(int)
QMetaObject::connectSlotsByName: No matching signal for on_SettingsDialog_Finished(int)
QMetaObject::connectSlotsByName: No matching signal for on_SearchDialog_Finished(int)
QMetaObject::connectSlotsByName: No matching signal for on_OfflineDialog_Finished(int)
QMetaObject::connectSlotsByName: No matching signal for on_CreateChatroomDialog_Finished(CreateChatroomDialog*)
qt.qpa.wayland: EGL not available
Error initializing OpenGL context sharing.
Puyolib: Debug Log was successfully created

QObject::connect(QAction, GameWidget): invalid nullptr parameter
Segmentation fault (core dumped)
```
What's interesting is that the client window seems to open but the main sim doesn't work due to the lack of OpenGL?
